
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

#JWT config
jwt.secret=a_very_secre_key_we_wanted_to_use
jwt.expiration=288000000
